<?php                                                                                                                                                                                                              
/**                                                                                                                                                                                                                
 * Plugin Name:         My Awesome New App                                                                                                                                                                         
 * Plugin URI:          https://yourdomain/wherever-you-keep-the-app-readme-file                                                                                                                                   
 * Description:         Some great app that I made and it's so great it'll make your life great!                                                                                                                   
 * Version:             1.0.0                                                                                                                                                                                      
 * Author:              Steve Whitmore                                                                                                                                                                             
 * Author URI:          https://stevewhitmore.dev                                                                                                                                                                  
 *                                                                                                                                                                                                                 
 * Be sure to rename the folder this file is in and this file to match what your plugin will be called. The names must be the same so WordPress knows where to look.                                               
 */                                                                                                                                                                                                                
                                                                                                                                                                                                                   
function load_ng_scripts() {                                                                                                                                                                                       
    wp_enqueue_style( 'ng_styles', plugin_dir_url( __FILE__ ) . 'dist/my-awesome-new-app/styles.somehash.css' );                                                                                                   
    wp_register_script( 'ng_main', plugin_dir_url( __FILE__ ) . 'dist/my-awesome-new-app/main.somehash.js', true );                                                                                                
    wp_register_script( 'ng_polyfills', plugin_dir_url( __FILE__ ) . 'dist/my-awesome-new-app/polyfills.somehash.js', true );                                                                                      
    wp_register_script( 'ng_runtime', plugin_dir_url( __FILE__ ) . 'dist/my-awesome-new-app/runtime.somehash.js', true );                                                                                          
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
add_action( 'wp_enqueue_scripts', 'load_ng_scripts' );                                                                                                                                                             
                                                                                                                                                                                                                   
function attach_ng() {                                                                                                                                                                                             
    wp_enqueue_script( 'ng_main' );                                                                                                                                                                                
    wp_enqueue_script( 'ng_polyfills' );                                                                                                                                                                           
    wp_enqueue_script( 'ng_runtime' );                                                                                                                                                                             
                                                                                                                                                                                                                   
    return "<app-root></app-root>";                                                                                                                                                                                
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
add_shortcode( 'ng_wp', 'attach_ng' );                                                                                                                                                                             
                                                                                                                                                                                                                   
// Add the shortcode [vue_wp] to any page or post.                                                                                                                                                                 
// The shorcode can be whatever. [ng_wp] is just an example.                                                                                                                                                       
?>    